### ISSUE TITLE
Error installing Django from Ansible - Page 28

### ISSUE THREAD

**Issue by dr7tbien** [geerlingguy/ansible-for-devops#100]
Hi.
In page 28 "Configure groups of servers, or individual servers" there is an Ansible code to install Django:

####################################################
ansible` app -b -m yum -a "name=MySQL-python state=present"
ansible app -b -m yum -a "name=python-setuptools state=present"
ansible app -b -m easy_install -a "name=django state=present"
###################################################

The 3th line throw the following error:

################################################################
192.168.60.4 | FAILED! => {
    "changed": false, 
    "msg": "\n==========================\nUnsupported Python version\n==========================\n\nThis version of Django requires Python 3.4, but you're trying to\ninstall it on Python 2.7.\n\nThis may be because you are using a version of pip that doesn't\nunderstand the python_requires classifier. Make sure you\nhave pip >= 9.0 and setuptools >= 24.2, then try again:\n\n    $ python -m pip install --upgrade pip setuptools\n    $ python -m pip install django\n\nThis will install the latest version of Django which works on your\nversion of Python. If you can't upgrade your pip (or Python), request\nan older version of Django:\n\n    $ python -m pip install \"django<2\"\nerror: Setup script exited with 1\n"
}
192.168.60.5 | FAILED! => {
    "changed": false, 
    "msg": "\n==========================\nUnsupported Python version\n==========================\n\nThis version of Django requires Python 3.4, but you're trying to\ninstall it on Python 2.7.\n\nThis may be because you are using a version of pip that doesn't\nunderstand the python_requires classifier. Make sure you\nhave pip >= 9.0 and setuptools >= 24.2, then try again:\n\n    $ python -m pip install --upgrade pip setuptools\n    $ python -m pip install django\n\nThis will install the latest version of Django which works on your\nversion of Python. If you can't upgrade your pip (or Python), request\nan older version of Django:\n\n    $ python -m pip install \"django<2\"\nerror: Setup script exited with 1\n"
}
#################################################################

I've tryed upgrade pip, do a symlink from pip to pip3.6, etc, with no results.

**Comment by dglinder** [comment]
What is the full version of the OS of your servers?

**Comment by geerlingguy** [comment]
(To @dglinder - The example in the book uses three Vagrant VMs running CentOS 7.)

@dr7tbien - The problem is the latest versions of Django require Python 3 (or 3.4 or later apparently)... but CentOS 7 ships with 2.7.x, and getting 3 can be burdensome ;)

So, to avoid that pain, the book was recently updated to use the following command to install Django (< version 2):

    ansible app -b -m easy_install -a "name=django<2 state=present"

I'd recommend for the purposes of testing to use this command instead of installing the latest Django, mostly because it's easier on any OS that doesn't ship with the latest Python by default (most of them).

In the future, the example will be updated for some later OS version or maybe Ubuntu 18 or so, and this will be a moot point, but for now, use the less than operator to make it work.

**Comment by geerlingguy** [comment]
See related: https://github.com/geerlingguy/ansible-for-devops/issues/81
