### ISSUE TITLE
lamp-infrastructure: CentOS 6 and no varnish6 repo

### ISSUE THREAD

**Issue by dino-github** [geerlingguy/ansible-for-devops#110]
Hi,
I was initially unable to get varnish to start.
Surprisingly the installed version was from Epel (2.1.5) and so was incompatible with the installed varnish config. After looking at the varnish repo file and the corresponding url on packagecloud.io
it seems that there is no varnish 6* repos for CentOS 6.

By adding 
varnish_version: 5.2
to the vars.yml I was able to get it to work.

I'm not sure if this the most effective approach to make varnish work in this case.

Best regards

**Comment by geerlingguy** [comment]
@dino-github - Thank you for posting this, and sorry about the trouble! I should really update that example to use CentOS 7 anyways, but you are correct, the only way to get Varnish running on CentOS 6 correctly is to use Varnish < 6, so setting:

```yaml
varnish_version: 5.2
```

(Or `4.1` or some other older version) should work.

**Comment by geerlingguy** [comment]
See also: https://github.com/geerlingguy/ansible-role-varnish/commit/c38f710348a18f630c661d063bfb51104526ed49#commitcomment-31157447

**Comment by txynidakis** [comment]
Hi I'm following your example in lamp-infrastructure 

in both vangrant (File supplied in the github repo) and aws, the playbook fails on the vanish role because it's install the minimum version

[vagrant@varnish ~]$ sudo varnishd -V
varnishd (varnish-2.1.5 SVN )
Copyright (c) 2006-2009 Linpro AS / Verdens Gang AS

the local repo file looks correct.

after upgrading varnish manually and updating the repo file using
curl -s https://packagecloud.io/install/repositories/varnishcache/varnish5/script.rpm.sh | sudo bash

I've tried putting 'varnish_version: "5.1"' in various locations with little success

defaults/main.yml
vars/main.yml
vars/RedHat.yml
tasks/main.yml

not sure where I'm going wrong?

**Comment by geerlingguy** [comment]
Working on this now. The best fix will be to use `geerlingguy/centos7` instead of `geerlingguy/centos6` for the Vagrant base box, but I haven't yet had the chance to test it fully to make sure everything works the same.

CentOS 6 is starting to lose support from some package maintainers (as is the case here, where Varnish is not publishing the latest versions for CentOS 6 anymore :( ), plus I'm trying to get all my examples onto newer OS releases in general.

**Comment by geerlingguy** [comment]
Also, @txynidakis to answer your specific question of where to put the var, it should go inside:

```
lamp-infrastructure/
  playbooks/
    varnish/
      vars.yml

That vars file is loaded and used when the Varnish provisioning is performed.
