### ISSUE TITLE
TASK - Build Docker images from Dockerfiles failed

### ISSUE THREAD

**Issue by wgong** [geerlingguy/ansible-for-devops#115]
Hi Jeff,
I have ubuntu 18.04 and anaconda3 and create py27 virtualenv

When trying to run docker project within your ansible-vagrant-examples repo
$ vagrant up --provision

got the following error while

I tried the suggestion from error msg by 
pip uninstall docker
pip uninstall docker-py
pip install docker
but the error msg remains, Do you have any suggestion? Thank you!

TASK [Build Docker images from Dockerfiles.] ***********************************
failed: [default] (item={u'directory': u'data', u'tag': u'data', u'name': u'data'}) => {"changed": false, "item": {"directory": "data", "name": "data", "tag": "data"}, "msg": "Cannot have both the docker-py and docker python modules installed together as they use the same namespace and cause a corrupt installation. Please uninstall both packages, and re-install only the docker-py or docker python module. It is recommended to install the docker module if no support for Python 2.6 is required. Please note that simply uninstalling one of the modules can leave the other module in a broken state."}
failed: [default] (item={u'directory': u'www', u'tag': u'flask', u'name': u'www'}) => {"changed": false, "item": {"directory": "www", "name": "www", "tag": "flask"}, "msg": "Cannot have both the docker-py and docker python modules installed together as they use the same namespace and cause a corrupt installation. Please uninstall both packages, and re-install only the docker-py or docker python module. It is recommended to install the docker module if no support for Python 2.6 is required. Please note that simply uninstalling one of the modules can leave the other module in a broken state."}
failed: [default] (item={u'directory': u'db', u'tag': u'mysql', u'name': u'db'}) => {"changed": false, "item": {"directory": "db", "name": "db", "tag": "mysql"}, "msg": "Cannot have both the docker-py and docker python modules installed together as they use the same namespace and cause a corrupt installation. Please uninstall both packages, and re-install only the docker-py or docker python module. It is recommended to install the docker module if no support for Python 2.6 is required. Please note that simply uninstalling one of the modules can leave the other module in a broken state."}
	to retry, use: --limit @/home/gong/vagrant/ansible-vagrant-examples/docker/provisioning/main.retry

PLAY RECAP *********************************************************************
default                    : ok=27   changed=2    unreachable=0    failed=1

**Comment by dino-github** [comment]
Hi,
I've just had a similar experience with the 'Building a Flask app with Ansible and Docker' example, which I solved (for me) with the following:

edit file:  provisioning/www/Dockerfile:
From:
RUN pip install flask flask-sqlalchemy mysql-python
To:
RUN pip install flask flask-sqlalchemy pymysql

Alternatively I removed the pip install line and changed the apt-get install line :
from:
RUN apt-get install -y libmysqlclient-dev python-dev python-pip
to:
RUN apt-get install -y libmysqlclient-dev python-dev python-pip python-flask python-flask-sqlalchemy python-pymysql iproute2

This worked for me  and uses the distro packages instead of pip repo ones

I also experimented with changing the base os:
from:
FROM geerlingguy/docker-ubuntu1604-ansible
to:
FROM geerlingguy/docker-ubuntu1804-ansible

which also worked (for me).

From other error messages I got whilst experimenting it seems that python-flask-sqlalchemy uses pymysql instead of python-mysql.

A quick note: passing the output of ansible through a script that converts \n to real linefeeds makes the error messages much easier to understand. As I understand perl more than python I used perl -p -e 's/\\n/\n/'

Best regards

**Comment by dino-github** [comment]
Oops, although the above was correct it doesn't actually answer your problem.

What I did to get rid of that error reported was to change the name of the installed docker python library in provisioning/setup.yml from docker-py to docker
ie 

from
- name: Install Docker Python library.
  pip: name=docker-py state=present
  become: yes
to
- name: Install Docker Python library.
  pip: name=docker state=present
  become: yes

After that I then did the steps I mentioned previously

Apologies for any confusion caused.

**Comment by geerlingguy** [comment]
@wgong / @dino-github - I'm guessing you may be working from an older version of the book. In version 1.15, the `pip` package was updated to `docker` (was originally `docker-py`). Can you check in the Preface (near the end) what version of the book you're reading?

Closing this now as I think it's been fixed in the latest version, but please let me know if it is still mis-typed somewhere else that I'm not finding.

**Comment by dino-github** [comment]
The book version I'm looking at is 1.17.
I was using ansible-vagrant-examples github repo. In it docker/provisioning/setup.yml appears to not have been updated:
cat  docker/provisioning/setup.yml 
---
# You can add users to the docker group to allow them to manage docker
# containers. This playbook uses sudo rather than the vagrant user because
# Ansible uses ControlPersist for SSH connections. The first time this playbook
# runs, the docker commands would fail if run by the vagrant user, since the
# persisted connection state isn't aware of the addition of the 'docker' group.
- name: Add vagrant user to docker group.
  user:
    name: vagrant
    groups: docker
    append: yes
  become: yes

- name: Install Pip.
  apt: name=python-pip state=installed
  become: yes

- name: Install Docker Python library.
  pip: name=docker-py state=present
  become: yes
