### ISSUE TITLE
[suggestion] Add examples how to configure WIndows via Ansible

### ISSUE THREAD

**Issue by mar1ged** [geerlingguy/ansible-for-devops#116]
I am not sure if this the proper way to make suggestions or if you accept suggestions at all ;-) 
You have a chapter in your book that explains how to install Ansible on Windows. I would like to learn more about how Ansible can configure WIndows systems.

By the way: I really like your book, I start to feel a little bit like a scrooge because I only paid the minimum necessary amount ;-) I guess I will ask my boss to buy a copy for our department, my book is one I bought for my personal use.

**Comment by geerlingguy** [comment]
This is definitely the best way to offer suggestions :)

I might or might not add more on Windows at some point, but it's definitely not in my short term plans, because I've never been a Windows administrator, and I would rather not write about and support a section of the book for something I don't have some good knowledge of.

For now, I'd refer you and your team to this pretty thorough guide in the documentation: https://docs.ansible.com/ansible/latest/user_guide/windows.html
