### ISSUE TITLE
Please add an index

### ISSUE THREAD

**Issue by ktry** [geerlingguy/ansible-for-devops#125]
:+1:. grep doesn't work on the paperback, please add an index :smile:

**Comment by geerlingguy** [comment]
I have had a few requests for this in the past, but it is just too hard to maintain a proper index with a book that is updated continuously. Unfortunately there are almost no tools for auto-generating indices for paperbacks, and until someone like LeanPub comes out with it, I just can't maintain it by hand (it would add an incredible amount of labor-intense updates every time I post an update).

**Comment by geerlingguy** [comment]
(For updates on LeanPub's support, please see: http://help.leanpub.com/author-help/how-can-i-create-an-index-for-my-leanpub-book)

**Comment by businessBoris** [comment]
This is a text book not a work of fiction one reads in bed.  It's not as if no other text book has an index.

I would like to inform you that most other text books provide Indices of various qualities. You seem to be blissfully unaware.

"Unfortunately there are almost no tools for auto-generating indices for paperbacks". It is simple untrue.

I wish I had not purchased this physical book. I followed the link you provided and it simple says "we can't be arsed ether".
Very very bad form.

**Comment by geerlingguy** [comment]
@businessBoris - I offer any reader who purchased the paperback not only a $1.99 copy of the Kindle book automatically (that discount is applied by Amazon), I also give anyone a DRM-free copy of the book on LeanPub if asked, since I vastly prefer having PDF/ePub/Kindle versions available when searching.

The sad fact is indices in most books are generated one time, ever, and aren't automatically updated over time—one of the reasons most print books come in rare 'editions'.

I've published over 40 revisions to the book, and to try to manually update an index for that many revisions would be next to impossible (I would spend more time doing that than updating the book's content—and adding many new chapters).

Unfortunately for some, that's the balance I've chosen to make sure the book remains relevant over many years (I initially published it in 2014, though all examples have been updated and new ones added, which work today). I still hope LeanPub may add the feature, because once they do, it will be much easier to maintain an index. But at this point I'm not quite holding my breath :)

**Comment by businessBoris** [comment]
I bought a physical textbook in good faith.

There are no warnings on the Amazon, or anywhere else I can find, that there is no way to easily use the physical book without buying a Kindle.

How **you** use **your **  book is completely irrelevant to me and the other user who made the issue post in 2019. I found the reply demeaning.

I have watched your videos with interest and wanted to buy the book that you mention therein. 

Please - for the sake of other physical book aficionados - put a warning on the Amazon physical book listing so that they don't have to waste time and money driving to the nearest return portal. 

The price of your book is irrelevant to me. I would probably buy it if it was twice the price. Telling me that there is no way to keep an index updated when I have been creating automatic indexes since 1990 for my CS projects doesn't fly.  You're adding insult to injury for what is actually I really decent book - except one that one must use as a bedtime story or laughable use in situ with a Kindle.

Please reconsider. 

Kind regards.

**Comment by dglinder** [comment]
@businessBoris - instead of berating @geerlingguy, take this as a challenge much like any opensource project!

Since producing an index is not something that he has the bandwidth to do right now, take one of the eBook versions available and write the Python/Bash/Java/Perl/whatever extraction tool and produce the index.  If it's something that can be worked into his workflow and automated as part of the LeanPub publication process, this would benefit this book's functionality AND quite possibly be an addition for other authors using LeanPub.

If ultimately it turns out the process is too complicated, or relies on something that only LeanPub has (dynamic page numbering triggers, etc.) then you are in the same predicament as @geerlingguy and have a deeper understanding of the challenges he has publishing.

**Comment by businessBoris** [comment]
@dglinder Please try very hard to focus on the issue at hand. 

I bought a book in good faith. The hardcopy book is not suitable for its intended purpose. The author tacitly agreed that it is not fit for its intended purpose by stating that he uses electronic aids to provide the search facilities required. He does not use the physical book.

You buy a car from me, a car dealer. You later find on delivery that the car is without an engine. I state that my children used it as a play thing, like the children in Chitty Chitty Bang Bang, the expectation of an engine in your car is a problem for you and not me. I suggest that I will lend you a bicycle which you can use as the requested transport, and ask if you have small children.

I am left with a book I must return because I economically cannot use it as is, this is a fact know to the author.  I will have wasted time to receive and return it and lost use of my capital whilst decide on a usable replacement. I am rightly perturbed where no reasonable warning has been given.

This is not to say that the project to create an index is not valuable and something I would be interested in assisting with.  It is, however, nothing whatsoever to do with the matter at hand.

**Comment by geerlingguy** [comment]
@businessBoris - Until LeanPub adds support for indices, I will not be adding one. I would rather not write my own Markdown-to-formatted PDF utility since LeanPub already does this, just so I can add an index. Some people are offended by a lack of index, but sadly, since it's a very small minority (according to the book reviews, which I typically check on once a month or so), it's unfortunately less of a priority for me to keep bothering LeanPub about it than trying to spend the few hours a month I have keeping the book updated and relevant over time.

Let's keep this issue's discussion on topic. **If anyone has any ideas for making an automated index that will integrate with a LeanPub + Amazon paperback publishing workflow, I'm all ears.** Until then, maybe email LeanPub and ask if they have any updated timeline on the feature.

But just coming in and giving a +1 comment that takes six paragraphs to basically say the same thing as the first issue is not helpful.
