### ISSUE TITLE
Chapter 1 page 4: Maybe discuss official package repos before pip install?

### ISSUE THREAD

**Issue by charlieok** [geerlingguy/ansible-for-devops#129]
In chapter 1 on page 4: “If your're running linux” first talks about installing ansible via pip.

Then we go on to find out that there are official yum packages for systems in the red hat family, and that there is an official apt repository you can set up for systems in the debian family.

Woudn't those packages be the first choice for people using those types of systems? It would make more sense to me to talk about those first, and then say, “if your needs are not met by those official packages, you can set up pip and install ansible using pip”.

If there's a compelling reason to prefer pip even when there are official distro-specific pacakges, it'd be helpful to clearly state why. Are the distro-specific packages not likely to get you an up-to-date version of ansible? If so, say that.

**Comment by geerlingguy** [comment]
Yes and no... so I'm of the opinion that the Pip repo is the most stable and foolproof way (in addition to being the most universal) to install Ansible on any mac or Linux workstation. I have installed it via apt, yum/dnf, brew, and pip on a large number of machines, and the number of times I've had installation issues with pip is dwarfed by the number I've had with others (e.g. repo issues, or packages not being updated in a timely fashion).

Now, this is spanning the past 6 years of usage—in that time the Ansible release process has improved dramatically. But old habits die hard, and I still prefer pip, mostly because it behaves the same everywhere I go, all the time.

Because of that, I think for now I'll leave it as is.

**Comment by charlieok** [comment]
My reason for diving into this was that I was writing cross-platform setup instructions for a couple projects that used ansible. I pretty much landed in the same place, mentioning that you can use an OS package if you want, but giving pip instructions.

https://github.com/zcash/zcash-gitian/blob/master/README.md
