### ISSUE TITLE
Mention VAGRANT_HOME

### ISSUE THREAD

**Issue by mok0** [geerlingguy/ansible-for-devops#135]
My $HOME is on an NFS mounted share, so the default behavior of Vagrant to place the virtual machines in `.vagrant.d` means that the quite large files containing the virtual machines need to travel quite a lot on the local network. I discovered that because the behavior of Vagrant was much more sluggish than it should be, when I followed the first few chapters. You have to place the virtual machines on a directory local to the server. You can do that by defining the VAGRANT_HOME environment variable. 

I think this should be mentioned in the book. The typical reader is savvy enough to know to place this definition in `.zshrc`, `.bashrc`  or similar.

**Comment by geerlingguy** [comment]
This is a good idea; one laptop I had only had a 64 GB main drive, so I had to put `VAGRANT_HOME` on an external SSD for similar reasons (not performance... but raw capacity). I'll try to figure out a good (early) place to put a tip/info box.

**Comment by geerlingguy** [comment]
This is something that I think only affects a smaller number of users, and since it's more of a niche use case (moving Vagrant home over to a different location than the default), I'm going to leave out any extra notes in the text itself, and hopefully people who want to do that can find the Vagrant docs or this issue for help with it.

Docs page on the setting: https://www.vagrantup.com/docs/other/environmental-variables.html#vagrant_home
