### ISSUE TITLE
Use secure and encrypted communication

### ISSUE THREAD

**Issue by stegr04** [geerlingguy/ansible-for-devops#137]
Hello, 

I think there is a typo in the section for "Use secure and encrypted communication", where it provides an example playbook for change the sshd_config. Line 20 of the example playbook has:
service: name=ssh state=restarted

I believe it should be sshd like this:
service: name=sshd state=restarted

I'm not sure if its different depending on the distribution you're using. I'm using CentOS 7.4. Really enjoying the book so far.

Cheers,
Gregg

**Comment by geerlingguy** [comment]
Thanks for posting this issue! The issue is that the example was written for Debian / Ubuntu, where the process is literally named `ssh`. But as you found, on CentOS, Fedora, Red Hat, etc., it's `sshd`.

So what I think I'll do is add a comment in that code example pointing out that the process name should be `sshd` if on a Red Hat derivative.

**Comment by stegr04** [comment]
cool. thanks for your attention!
