### ISSUE TITLE
install 'kubelet=1.13.1-00'' failed: E: Unable to correct problems, you have held broken packages

### ISSUE THREAD

**Issue by jendxb** [geerlingguy/ansible-for-devops#146]
TASK [geerlingguy.kubernetes : Install Kubernetes packages.] *******************
failed: [master] (item={'name': 'kubelet=1.13.1-00', 'state': 'present'}) => {"ansible_loop_var": "item", "cache_update_time": 1561909258, "cache_updated": false, "changed": false, "item": {"name": "kubelet=1.13.1-00", "state": "present"}, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'kubelet=1.13.1-00'' failed: E: Unable to correct problems, you have held broken packages

**Comment by atatevyan** [comment]
Same for me. Can't really run this example.

**Comment by torenware** [comment]
Looks like the problem is in kubernetes/vars/main.yml. It hard codes the versions of the kubernetes packages to 1.13.1.  That package is no longer on the current version of the debian box; current version is 1.13.8.  Updating this in the file appears to fix the problem.

I'll do up a PR, which should fix this.

**Comment by torenware** [comment]
PR149 passed Travis.

**Comment by geerlingguy** [comment]
Sorry about that! I'll take a look at that PR today. I will also likely update the K8s version in the example to latest 1.15.
