### ISSUE TITLE
Typo in chapter 3 > Deploy a version-controlled application > info block on p.41

### ISSUE THREAD

**Issue by rusnino** [geerlingguy/ansible-for-devops#176]
In chapter 3 - Ad-Hoc Commands > Deploy a version-controlled application > info block on p.41 there is wrong command:

> If you get a message saying “Failed to find required executable git”, you
will need to install Git on the server. To do so, run the ad-hoc command
ansible package -b -m yum -a "name=git state=present".

**Comment by geerlingguy** [comment]
Oops, I'm guessing when I was doing some updates to replace usages of the `yum` or `apt` modules which would be better suited to use the `package` module, I accidentally replaced the `app` inventory group with `package` (instead of replacing the `yum` module with `package`). The correct version should be:

> If you get a message saying "Failed to find required executable git", you will need to install Git on the server. To do so, run the ad-hoc command `ansible app -b -m package -a "name=git state=present"`.

Thanks, and this fix will be in the next version of the book!
