### ISSUE TITLE
[1.20] p. 49, item 5: description doesn't match with the content of the playbook

### ISSUE THREAD

**Issue by guntbert** [geerlingguy/ansible-for-devops#178]
In reference to the task using the `yum` module you describe the use of variables and `with_items` (both are used in the next task). 
This task doesn't use a loop at all.

**Comment by geerlingguy** [comment]
You're correct; that was in there because originally it was structured using `with_items` and a list of all the packages, but was updated to pass the package list straight to the `name` parameter since the original method is less preferred and will not perform as efficiently once Ansible 2.11 is released.

Thanks for opening this issue! I've fixed the issue in the text and it will be in the next set of updates that are published.
