### ISSUE TITLE
Book versions vs errata 

### ISSUE THREAD

**Issue by sirkubax** [geerlingguy/ansible-for-devops#180]
Hello

I give your book as a gift for the Training's I deliver in Poland :)
I was recently asked for a book version newer than 2015.

I found you have an errata, with already 20 minor-versions...
https://www.ansiblefordevops.com/errata

I was looking for any info what is the 'paper' book version. Is that 1.0?
`starting with the 1.0 release (as tracked on LeanPub).`

Is there any place where I could buy recent release of paper book?

**Comment by geerlingguy** [comment]
@sirkubax - Amazon.com has the latest version of the book (currently 1.20 as of this writing), and you can buy it and you'll get the latest version any time. Unfortunately because of their antiquated publishing system I'm not allowed to update the published date, so it will always say "October 2015" even though it's been updated 20 times since then.
