### ISSUE TITLE
remi epel commands don't work as 'vagrant' user in chapter 4 "Add extra repositories" example

### ISSUE THREAD

**Issue by peurKe** [geerlingguy/ansible-for-devops#184]
As "vagrant" user, theses commands doesn't works :
```
wget https://rpms.famillecollet.com/RPM-GPG-KEY-remi -O /etc/pki/rpm-gpg/RPM-GPG-KEY-remi
rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-remi
rpm -Uvh --quiet https://rpms.remirepo.net/enterprise/remi-release-7.rpm
yum install epel-release
yum --enablerepo=epel install npm
```

As "vagrant" user, theses commands works :
**--no-check-certificate** in order to allow unsecure wget on https
**rpms.remirepo.net** instead of rpms.famillecollet.com
**sudo** at the beginning of each command
```
sudo wget --no-check-certificate https://rpms.remirepo.net/RPM-GPG-KEY-remi -O /etc/pki/rpm-gpg/RPM-GPG-KEY-remi
sudo rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-remi
sudo rpm -Uvh --quiet https://rpms.remirepo.net/enterprise/remi-release-7.rpm
sudo yum install epel-release
sudo yum --enablerepo=epel install npm
```

**Comment by arashpath** [comment]
Also **remi-release-7.rpm** requires **epel-release** so same must be installed first
```bash
# Installing epel-relese first
sudo yum install epel-release
sudo yum --enablerepo=epel install npm
# Then Install remi
sudo wget --no-check-certificate https://rpms.remirepo.net/RPM-GPG-KEY-remi -O /etc/pki/rpm-gpg/RPM-GPG-KEY-remi
sudo rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-remi
sudo rpm -Uvh --quiet https://rpms.remirepo.net/enterprise/remi-release-7.rpm
```

**Comment by geerlingguy** [comment]
In the time since posting, it seems the https://rpms.remirepo.net/RPM-GPG-KEY-remi URL has a valid certificate, so that command doesn't need the `--no-check-certificate` flag.

Note that I would like to keep the commands without `sudo`, so in the text I updated the line above the script to mention it is meant to be run on a CentOS 7 server as the `root` user.

Thanks for pointing this out, I'll have it fixed in the next book update, coming very soon!
