### ISSUE TITLE
drupal playbook - Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user

### ISSUE THREAD

**Issue by nqui** [geerlingguy/ansible-for-devops#200]
TASK [Install Drupal dependencies with Composer.] ******************************
fatal: [default]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: changing ownership of '/var/tmp/ansible-tmp-1580524622.7705758-209663871137752/': Operation not permitted\nchown: changing ownership of '/var/tmp/ansible-tmp-1580524622.7705758-209663871137752/AnsiballZ_command.py': Operation not permitted\n}). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}

running against the provided vagrant vm setup - wrote the playbook on my own, ran into some issues, so i grabbed the playbook.yml provided in the drupal dir.

**Comment by nqui** [comment]
the part of the playbook that i'm having issue with:

```
- name: Install Drupal dependencies with Composer.
      command: >
        /usr/local/bin/composer install
        chdir={{ drupal_core_path }}
        creates={{ drupal_core_path }}/vendor/autoload.php
      become_user: www-data
```

**Comment by geerlingguy** [comment]
When you're running against Vagrant, what user are you using for the connection itself? For the playbook itself, it's using `become` to run as root via sudo: https://github.com/geerlingguy/ansible-for-devops/blob/master/drupal/provisioning/playbook.yml#L3

**Comment by nqui** [comment]
I'm using the `vagrant` user. Here's the last few lines of my `/etc/ansible/hosts`

```
[drupal:vars]
ansible_ssh_user=vagrant
ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key
```

I've tried not having a user defined (I believe it will fallback to my local user?) & I still ran into the same problem.

Starting fresh - Cloning the repo and using `vagrant up` in the drupal directory, I get the same error.

**Comment by nqui** [comment]
Commenting out the `become_user: www-data` in the last 2 tasks fixed it, obviously not ideal & secure for a production application. I'm still interested in why this is failing.

I'm not familiar with drupal, but do we have to run the last 2 tasks `Install Drupal dependencies with Composer.` & `Install Drupal.` with `become_user: www-data`? Can we just change ownership & group on the files that get created?

**Comment by geerlingguy** [comment]
This was very recently changed: https://github.com/geerlingguy/ansible-for-devops/commit/858e10d1985a916d5a8b5b54cf58a4bcfdb1f817

The reason I switched from that approach was it broke idempotence—since Drupal manages file permissions in a way that would make it impossible to set ownership globally on the files directory (some dirs and files within are different permissions), it was easier to make those commands run as `www-data`. It _should_ work that way, but it sounds like at least in your case, it didn't.

I'll try to debug this and see if I can get it to reproduce locally.

**Comment by lucky01001** [comment]
Same issue for me, ansible 2.9.6. I tried also with a fresh clone.

**Comment by geerlingguy** [comment]
@nqui and @lucky01001 - are you running on macOS, Linux, or Windows?

**Comment by lucky01001** [comment]
macOS

**Comment by sgrech** [comment]
I can report the same issue on macOS

**Comment by nqui** [comment]
@geerlingguy macOS Catalina 10.15.3

**Comment by sgrech** [comment]
Issue replicated on Linux Mint 19

**Comment by sgrech** [comment]
Reading the docs on [becoming an unprivileged user](https://docs.ansible.com/ansible/latest/user_guide/become.html#risks-of-becoming-an-unprivileged-user), it seems this is an intended behavior due to security issues. The documentation lists three ways to properly address this, but I think they would require changing the `become` strategy used in this playbook. 

Since this is a test playbook and not intended to use for production, I opted to use the workaround suggested by setting an ansible configuration flag `allow_world_readable_tmpfiles`

There are multiple ways to add this config file, I opted for the following method:

- add provisioning/ansible.cfg file with the following content:

```cfg
[defaults]
allow_world_readable_tmpfiles = true
``` 

- add `ansible.config_file = "provisioning/ansible.cfg"` in the Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "geerlingguy/ubuntu1604"
  config.vm.network :private_network, ip: "192.168.88.8"
  config.vm.hostname = "drupal.test"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
  end

  # Ansible provisioning.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.config_file = "provisioning/ansible.cfg"
  end
end
```

This allowed the Vagrant to successfully provision the VM on my Linux Mint machine, but for some reason it was hanging on macOS with the task `TASK [Install Drupal dependencies with Composer.]`. I am not sure if this issue was due to my local environment (python version, global configs, etc..) but I will continue investigating.

**Comment by searsaw** [comment]
Can confirm seeing the same issue on MacOS.

```
$ uname -a
Darwin hostname.lan 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin

$ ansible --version
ansible 2.9.6
  config file = None
  configured module search path = ['/Users/username/ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.6_1/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Mar 11 2020, 00:29:50) [Clang 11.0.0 (clang-1100.0.33.17)]

$ vagrant --version
Vagrant 2.2.7

**Comment by jjclaude** [comment]
> 

> 
> Reading the docs on [becoming an unprivileged user](https://docs.ansible.com/ansible/latest/user_guide/become.html#risks-of-becoming-an-unprivileged-user), it seems this is an intended behavior due to security issues. The documentation lists three ways to properly address this, but I think they would require changing the `become` strategy used in this playbook.
> 
> Since this is a test playbook and not intended to use for production, I opted to use the workaround suggested by setting an ansible configuration flag `allow_world_readable_tmpfiles`
> 
> There are multiple ways to add this config file, I opted for the following method:
> 
>     * add provisioning/ansible.cfg file with the following content:
> 
> 
> ```haproxy-config
> [defaults]
> allow_world_readable_tmpfiles = true
> ```
> 
>     * add `ansible.config_file = "provisioning/ansible.cfg"` in the Vagrantfile
> 
> 
> ```ruby
> # -*- mode: ruby -*-
> # vi: set ft=ruby :
> 
> VAGRANTFILE_API_VERSION = "2"
> 
> Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
>   config.vm.box = "geerlingguy/ubuntu1604"
>   config.vm.network :private_network, ip: "192.168.88.8"
>   config.vm.hostname = "drupal.test"
>   config.ssh.insert_key = false
> 
>   config.vm.provider :virtualbox do |v|
>     v.memory = 1024
>   end
> 
>   # Ansible provisioning.
>   config.vm.provision "ansible" do |ansible|
>     ansible.playbook = "provisioning/playbook.yml"
>     ansible.config_file = "provisioning/ansible.cfg"
>   end
> end
> ```
> 
> This allowed the Vagrant to successfully provision the VM on my Linux Mint machine, but for some reason it was hanging on macOS with the task `TASK [Install Drupal dependencies with Composer.]`. I am not sure if this issue was due to my local environment (python version, global configs, etc..) but I will continue investigating.

![drupal-lamp-provision](https://user-images.githubusercontent.com/3969854/77947417-e1107d00-7291-11ea-8c37-f5ae69af9ba0.PNG)
![drupal-lamp-Vagrantfile](https://user-images.githubusercontent.com/3969854/77947418-e1107d00-7291-11ea-9c17-8244ada5a7af.PNG)

Hi, I was able to apply your fix @sgrech. I am running Ansible 2.4 (long story short, I have 2.9.6 running on the machine I will have my production playbooks on, but I am using 2.4 on the testbed I am using for this eBook)

![drupal-lamp-ansible-2 4 2](https://user-images.githubusercontent.com/3969854/77947639-3c426f80-7292-11ea-8d22-7d216e2d4387.PNG)

In cases like this I usually try to go to the sudoers file and add the user there, but I have trouble getting SSH access to the VM since it's inside two other VMs (Russian doll situation -> 1) Local machine, 2) VMWare Workstation VM Centos7 3) VirtualBox Vagrant VM) When I set up Vagrant on my local machine, I was able to get inside the Vagrant VM since it was only one hop, but since it's now two hops, I haven't been able to get it to work. I added entries in the /etc/hosts file but that didn't work.

At any rate, that's how I was able to resolve it. Thanks @sgrech

**Comment by DrAregCodecio** [comment]
Ran into this issue as well. Just started the book with the livestreams! I've also implemented `allow_world_readable_tmpfiles = True` as a workaround.
Running on `fedora31` with ansible `2.9.6`

**Comment by MacFlurry** [comment]
@DrAregCodecio 

> When pipelining is enabled, Ansible doesn’t save the module to a temporary file".
 allow_world_readable_tmpfiles is irrelevant when pipelining is enabled and the documenation suggest to enable `pipelining`.
in ansible.cfg just enable `pipelining = True` and disable `allow_world_readable_tmpfiles`

**Comment by MacFlurry** [comment]
@nqui read my comment above [👆🏾](https://github.com/geerlingguy/ansible-for-devops/issues/200#issuecomment-611231063)

**Comment by DrAregCodecio** [comment]
> @DrAregCodecio
> 
> > When pipelining is enabled, Ansible doesn’t save the module to a temporary file".
> 
> `allow_world_readable_tmpfiles` is irrelevant when pipelining is enabled and the documenation suggest to enable `pipelining`.
> in `ansible.cfg` just **enable** `pipelining = True` and **disable** `allow_world_readable_tmpfiles`.
> I'm using `ansible 2.9.6`

Thanks for the feedback. Tested this and it works.

**Comment by MacFlurry** [comment]
@nqui could you please close this issue ?
