### ISSUE TITLE
Missing a word (or two) in Gluster chapter 8, pg 229

### ISSUE THREAD

**Issue by kevinbowen777** [geerlingguy/ansible-for-devops#203]
The sentence reads:

> replicas tells Gluster how many replicas to ensure exist; this number can vary
depending on how many servers you have in the brick’s cluster, and how
tolerance you have for server outages.

It should probably read "...,and how much tolerance you have..."

The phrase "...tells Gluster how many replicas to ensure exist;..." reads awkwardly. I'm not certain how that should parse. s/to ensure/should/  ?

**Comment by geerlingguy** [comment]
Yeah, both of your suggestions make it read better. I think because I name so many task "_Ensure_ xyz happens.", that word leaks into other sentences, even when that makes them a bit jumbled!

Thanks for the suggestions, I've fixed both lines, and the changes will be in the next batch of book updates.
