### ISSUE TITLE
[1.22] p. 285 - About validating /etc/sudoers

### ISSUE THREAD

**Issue by lustoerk** [geerlingguy/ansible-for-devops#224]
Hey, thanks for your great work and for making it free!

I have one suggestion about page 285:
"validate" can be used for "lineinfile" as well, not just for the  "copy" module. You could remove the whole paragraph about "using caution with lineinfile" and just show how validate could be used for both modules.

**Comment by geerlingguy** [comment]
@lustoerk - Good catch! I never realized `validate` could be passed to `lineinfile` until just now. I thought maybe it was added somewhat recently, but glancing through Ansible's git history, it's been there at least _six_ years!

I'll have this fixed in the next version of the book, 1.23. Thanks again!
