### ISSUE TITLE
Dynamic inventory yaml

### ISSUE THREAD

**Issue by sagar-kolli** [geerlingguy/ansible-for-devops#262]
Can you provide python code for Ansible dynamic inventory to generate yml inventory file

**Comment by geerlingguy** [comment]
@sagar-kolli - I have a python inventory script example from the book here: https://github.com/geerlingguy/ansible-for-devops/blob/master/dynamic-inventory/custom/inventory.py

Note that it generates JSON output (which is technically compatible with YAML since JSON is valid YAML), but it's meant to output directly into Ansible's inventory system.

If you want to generate a YAML file with a structure valid for use as a separate inventory file, then you can probably do that using Python and Jinja2.

Otherwise, for other advanced use cases, check out Ansible's documentation on inventory plugins: https://docs.ansible.com/ansible/latest/plugins/inventory.html
