### ISSUE TITLE
helm.yml playbook in March 20th 2020 book

### ISSUE THREAD

**Issue by mandrews4** [geerlingguy/ansible-for-devops#267]
The top of page 400 of the pd begins with a subsection "Managing Kubernetes Applications with Helm". This subsection contains the lines 1-38 of the helm.yml playbook.

This playbook seems to resume half way down page 402 with lines 38-70.

I believe that lines 38-70 should all be incremented by two to continue from the previous 1-38 lines.

**Comment by geerlingguy** [comment]
@mandrews4 - Thanks for finding this error—I'm actually going to be rewriting the Helm section, since Ansible's `community.kubernetes` collection now includes a new Helm module that I'd rather use. See https://github.com/geerlingguy/ansible-for-devops/issues/266 — closing this issue as a duplicate since this will be fixed by the rewrite. Thanks!
