### ISSUE TITLE
Chapter 3 - Ad-Hoc Commands

### ISSUE THREAD

**Issue by GiovanniMet** [geerlingguy/ansible-for-devops#312]
On page 20, you create a centos8 machine, on page 21 you said is centos7.

**Comment by janvanveldhuizen** [comment]
I noticed that too.
Moreover, centos8 gave an error because I am having vbguest vagrant plugin. It works well with centos7.

When using centos7 I had to add an additional command on page 30 to get the pip install working: `ansible app -b -m easy_install -a "name=pip state=present"`

**Comment by geerlingguy** [comment]
Oops! I'll be sure to get this fixed by the next version of the book. Thanks for discovering this error.

**Comment by hmoffatt** [comment]
On a related note, because chapter 3 uses centos8 but chapter 2 uses centos7, it has to download another whole box here.

**Comment by hmoffatt** [comment]
And also, the ```ansible multi -b -m yum -a "name=chrony state=present"``` command reports SUCCESS immediately rather than CHANGED, I suppose because the new image already installed the package.

**Comment by akamch** [comment]
Another minor inconsistency is the ntpd's presence in the Ansible's output on page 29 after enabling chronyd.

**Comment by typ-ex** [comment]
> I noticed that too.
> Moreover, centos8 gave an error because I am having vbguest vagrant plugin. It works well with centos7.
> 
> When using centos7 I had to add an additional command on page 30 to get the pip install working: `ansible app -b -m easy_install -a "name=pip state=present"`

I ended up explicitly stating that the python interpreter was python3.  I did notice that the centos image might come with python2, and then install python3 via yum.

**Comment by szTheory** [comment]
On page 31, the pip install of Django failed (Cent OS7)

```
192.168.60.5 | FAILED! => {                                                                                                                            
    "ansible_facts": {                                                                                                                                 
        "discovered_interpreter_python": "/usr/bin/python"                                                                                             
    },                                                                                                                                                 
    "changed": false,                                                                                                                                  
    "msg": "Unable to find any of pip2, pip to use.  pip needs to be installed."                                                                       
}  
```

Fixed it by specifying the executable path of pip3 with `executable=$(which pip3)`

```bash
ansible app -b -m pip -a "name=django<4 state=present executable=$(which pip3)"
```

**Comment by szTheory** [comment]
On page 32, after installing python3-PyMySQL (CentOS7) with command

```bash
ansible db -b -m yum -a "name=python3-PyMySQL state=present"
```

And then running command:

```bash
ansible db -b -m mysql_user -a "name=django host=% password=12345 priv=*.*:ALL state=present"
```

Got this error:

```
192.168.60.6 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },                                                                                                                                                 
    "changed": false,                                                                                                                                      "msg": "The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required."                                                  
}     
```

Had to install the python 2 version of PyMySQL to get it to work (note the `name=python2-PyMySQL`)

```bash
ansible db -b -m yum -a "name=python2-PyMySQL state=present"
```

The book says to use CentOS7 and CentOS8 at different points so I'm not sure if that's causing the issues. I went with CentOS7 since that's what the book starts with.

**Comment by typ-ex** [comment]
> > I noticed that too.
> > Moreover, centos8 gave an error because I am having vbguest vagrant plugin. It works well with centos7.
> > When using centos7 I had to add an additional command on page 30 to get the pip install working: `ansible app -b -m easy_install -a "name=pip state=present"`
> 
> I ended up explicitly stating that the python interpreter was python3. I did notice that the centos image comes with python2.
> After installing the package via yum for python3-x I ended up explicitly stating that the python interpreter to be /usr/bin/python3 in hosts.ini

This whole chapter in general should be looked at.  On page 35 I've had to switch the interpreter back to /usr/bin/python

**Comment by typ-ex** [comment]
Finally managed to take a deep dive into chapter 3.  Assuming everything is done in order
Anything done via yum/package would have to be done with python2 because ansible will suggest dnf for python3, and dnf isn't in the CentOS image.
Anything done via pip/mysql_user will need python3 because of the yum installs are python3 related.
None of the wildcard commands worked out, returned non-zero code.
Anything cron related needs python2 cause of the use of selinux

Used ubuntu, and installed ansible via pip3 because apt was out of date.  Using an updated ansible may have helped with getting chronyd status and restarting the chronyd service.  I was hoping to consistently use python3 or 2, but it seems like the lack of dnf in the CentOS image would prevent it.

**Comment by typ-ex** [comment]
Last post
All of what I noted is corrected in the CentOS 8 image.  Python 3 is already installed, and there's no need to explicitly define the interpreter in the host file or elsewhere.

It's odd when running the commands it looks like python2 is the interpreter, but everything ran as should without modifications.  

Please use the centos 8 image.

**Comment by ddefrancesco** [comment]
> On page 31, the pip install of Django failed (Cent OS7)
> 
> ```
> 192.168.60.5 | FAILED! => {                                                                                                                            
>     "ansible_facts": {                                                                                                                                 
>         "discovered_interpreter_python": "/usr/bin/python"                                                                                             
>     },                                                                                                                                                 
>     "changed": false,                                                                                                                                  
>     "msg": "Unable to find any of pip2, pip to use.  pip needs to be installed."                                                                       
> }  
> ```
> 
> Fixed it by specifying the executable path of pip3 with `executable=$(which pip3)`
> 
> ```shell
> ansible app -b -m pip -a "name=django<4 state=present executable=$(which pip3)"
> ```
> 
> After that had to use `python3`, so the next command became
> 
> ```shell
> ansible app -a "python3 -m django --version"
> ```
Or (because in CentOS7 $(which pip3) yields always /anaconda3/bin/pip3 --> "File not present") : set variable in hosts.ini like this:
```
...
[app:vars]
ansible_python_interpreter=/usr/bin/python3

```
and just 

```
ansible app -b -m pip -a "name=django<4 state=present"

```

then control django version.

**Comment by ddefrancesco** [comment]
Also to run mysql_user module, I had to add python3 interpreter punctually on ansible statement, like this:

`ansible db -b -m mysql_user -a "name=django host=% password=12345 priv=*.*:ALL state=present" -e 'ansible_python_interpreter=/usr/bin/python3'`

So, imho, for CentOS7 (which, for good or for worse, is still the enterprise de facto standard) major changes are two. 

In my opinion @geerlingguy should create two branches or tags, one for CentOS7 and one for CentOS8 in order to 
avoid confusion and issues.
mtc

**Comment by StevenKitavi** [comment]
The Fix is Upgrading to Centos/8 I Upgraded to Centos/8 and fixed all error
Fastest Fix use geerlingguy/centos8 as is that's the Bug fix Geerling talked about fixing 
Vagrant destroy
modify 
config.vm.box="geerlingguy/centos8" it works 
add host_key_checking = False Line to ansible.cfg to avoid ssh errors
Hope that helps

**Comment by lorezi** [comment]
An upgrade to CentOs 8 fixed the issue for me

**Comment by geerlingguy** [comment]
Sorry about all this... for some reason last time I had a go at that chapter, I only halfway updated all the examples for CentOS 8. Now that Rocky Linux 8 is my preferred 'RHEL-derivative-to-test-in' distro, I'm going through and _hopefully_ fixed the lingering bits through a number of other issues. I'll hopefully get all that out the door in an update tonight.
