### ISSUE TITLE
Broken link ch4 on leanpub

### ISSUE THREAD

**Issue by silvanob** [geerlingguy/ansible-for-devops#354]
> The greater-than sign (>) immediately following the command: module directive tells YAML “automatically quote the next set of indented lines as one long string, with each line separated by a space”. It helps improve task readability in some cases. There are different ways of describing configuration using valid YAML syntax, and these methods are discussed in-depth in the [YAML Conventions and Best Practices](https://leanpub.com/ansible-for-devops/OEBPS/chap20.xhtml#yaml-best-practices)
 section in Appendix B.

In chapter 4 links to https://leanpub.com/ansible-for-devops/OEBPS/chap20.xhtml#yaml-best-practices, but this page can not be found on LeanPub. 
![image](https://user-images.githubusercontent.com/22224656/99197778-d78e4380-2794-11eb-9a8e-f4d3b54feee6.png)

**Comment by geerlingguy** [comment]
@smbiemans - Interesting... Are you reading the book via PDF, epub, or some other means? And what device are you using to read it? That is an internal link, and I use them sparingly because I honestly don't know how they work across all the different e-readers and platforms.

**Comment by smbiemans** [comment]
This is on LeanPub on my laptop in Firefox.

**Comment by geerlingguy** [comment]
@silvanob - Aha, so that's an internal book reference, and really it should render in ePub, PDF, and mobi correctly—it looks like you may have found a bug in LeanPub's online book viewer.

I just tested the link in Preview on my Mac, and it worked correctly there:

<img width="381" alt="Screen Shot 2022-04-14 at 11 12 14 PM" src="https://user-images.githubusercontent.com/481677/163517074-a1653ad6-42d9-45ca-85d5-3ea0ad9421f1.png">

As it's not something I can fix, I'd recommend following up by emailing LeanPub support if it's still an issue. Thanks!
