### ISSUE TITLE
Add custom index.html file for balancer example

### ISSUE THREAD

**Issue by doughnet** [geerlingguy/ansible-for-devops#45]
This is great.  I think it would be great if you had a custom index.html used which would provide the IP# of the backend webserver it loads.  This way it can visually show which of the backend webserver it loaded.

I noticed in one of your other examples you did something like this; but doing it for this example would be the best.

**Didn't realize this wouldn't display for the deployments-balancer folder specifically**

**Comment by geerlingguy** [comment]
Sounds reasonable! Thanks for the suggestion.

**Comment by geerlingguy** [comment]
Looking back on this; for this particular example I have the user using `curl -Is http://192.168.4.2/` and checking the cookie value to see which app server is serving the request. Since this example is early in the book and meant to mostly show how to drop a server out of the rotation—and since later examples do (as you mention) have more advanced 'app' functionality that displays the IP—I'm going to leave the example as is for now.
