### ISSUE TITLE
2nd Ed, PDF p35, 'package' command has yum servers issue (CentOS 8 EOL)

### ISSUE THREAD

**Issue by mcheck** [geerlingguy/ansible-for-devops#453]
On p35 of 2nd Ed.:
`ansible app -b -m package -a "name=git state=present"`

```
192.168.57.4 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "msg": "Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist",
    "rc": 1,
    "results": []
}
192.168.57.5 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "msg": "Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist",
    "rc": 1,
    "results": []
}
```

Servers created as CentOS8s.

In the machine: 
```
[vagrant@orc-app1 ~]$ sudo yum update -y
CentOS Linux 8 - AppStream                                          152  B/s |  38  B     00:00
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

Stackexchange suggests this is a `resolv.conf` issue, but even replacing `resolv.conf` with 
```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

Same error results.

**Comment by dglinder** [comment]
The error message you're receiving:

```
Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

is from `yum`, not Ansible - this is a problem with your `app` servers installation or configuration - you will need to ask on a CentOS support forum.

**Comment by geerlingguy** [comment]
This seems to be the result of CentOS 8's EOL. At some point I may switch the examples to Rocky Linux 8 instead. (Yet another effect of the CentOS 8 rug-pull, grr...).

This seems to have started happening within the past week.

**Comment by geerlingguy** [comment]
See https://github.com/geerlingguy/packer-boxes/issues/80 — I'm planning on adding a rockylinux8 build soon.

**Comment by advancedluser** [comment]
Hey there, I'm really enjoying your book and videos :)

Wanted to add, that this issue is present in other places. I just faced it on page 20 and in the config file here on [GitHub](https://github.com/geerlingguy/ansible-for-devops/blob/master/orchestration/Vagrantfile) you have geerlingguy/centos8, but after in the book and in the videos on YouTube you talk about CentOS 7.

In the screenshot, line 8 in the code and the last line of text at the bottom.

![image](https://user-images.githubusercontent.com/102283807/160290617-09578ef7-1197-4c8a-95b7-cb2c6937b193.png)

**Comment by geerlingguy** [comment]
I have these references fixed in the manuscript. I hope to have an update out tonight!
