### ISSUE TITLE
Question: Role documentation, standards or best practices?

### ISSUE THREAD

**Issue by sierkje** [geerlingguy/ansible-for-devops#47]
First of all, thanks and gratitude for writing that extremely helpful and very well written book, Jeff.

I don't know whether this issue queue is the appropriate place to ask about something that isn't example related, and not specifically covered in the book, but I couldn't think of a better place to ask.

My question is related to a role that I intend to share via Galaxy (installing / configuring hiawatha webserver incl. virtual hosts -- the few available roles don't work for me). But the question is, I think, of more general interest (at least for me): 

**What is the best place to document role variables, tasks, etc.?**

There are several ways to go about this, that I can think of:
* Should we just add documentation in the README file?
* Should we add comments in the defaults/main.yml and tasks/main.yml? (And if so, are there standards for this that allow documentation to be extracted?)
* Should we add documentation (markdown) files that we link to from the README file? (And if so, are there standards for how to name these files and for where to place them?)
* Should we add external documentation by creating or linking to (for example) a ReadTheDocs project?

Or is there another, better or preferred way/place to do this, that I haven't found about yet?

**Comment by geerlingguy** [comment]
Great questions! This is actually something openly being discussed in the Ansible community, and the best place to focus your efforts (or at least hit the 'Subscribe' button) is here: https://github.com/ansible/proposals/issues/19

For my own roles (example: [`geerlingguy.apache`](https://github.com/geerlingguy/ansible-role-apache)), I generally do the following:

  - Add a few general comments and possibly an inline commented example or two inside `defaults/main.yml`
  - Document every single variable (unless there's a block of similar variables that are self-explanatory) inside README.md (since this will be the welcoming text on the GitHub repo and on Galaxy for the role).
  - Document at least one or two special use cases or examples in the README.md.
  - Use the role tests (automated via Travis CI) as an extra 'in use' example or two—you'll be forced to always make sure these examples are correct/working if they're using Travis to build the role!

For really, really complicated roles, you could consider integrating with external docs, but I'd still store the actual docs in the project (I hate having a separate project/site to manage docs vs. the actual code...).
