### ISSUE TITLE
'deployments' README.md incorrect

### ISSUE THREAD

**Issue by gpolyn** [geerlingguy/ansible-for-devops#49]
[README.md](https://github.com/geerlingguy/ansible-for-devops/blob/master/deployments/README.md) for 'deployments' section may be incorrect at the following line:

_Run ansible-galaxy install -r requirements.yml in this directory to get the required Ansible roles._

`vagrant up` after performing the aforementioned step had the following result:
```
ERROR! the role 'geerlingguy.git' was not found in /Users/gallagherpolyn/ansible/ansible-for-devops/deployments/playbooks/roles:/Users/gallagherpolyn/ansible/ansible-for-devops/deployments/playbooks:/Users/gallagherpolyn/ansible/ansible-for-devops/deployments

The error appears to have been in '/Users/gallagherpolyn/ansible/ansible-for-devops/deployments/playbooks/provision.yml': line 9, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - geerlingguy.git
      ^ here
```
The following command works, instead, but may break Ansible best practices:

`ansible-galaxy install --roles-path=playbooks/roles -r requirements.yml`

**Comment by geerlingguy** [comment]
Thanks! I may update the instructions and/or include an `ansible.cfg` file in each of these playbooks to indicate roles should be installed within the playbook dir instead of globally (which requires `sudo` privileges, usually).

**Comment by geerlingguy** [comment]
I just tested this on my Mac, and it seemed to work okay:

    ansible-galaxy install -r requirements.yml

Though I have a custom `roles_path` in my system `ansible.cfg` that points to a directory over which I have read/write access:

```
[defaults]
roles_path = ~/Dropbox/ansible-roles
```

I'm wondering if maybe the ansible-galaxy install command had an error message when you ran it?

For now, I'm going to close this ticket as a 'won't fix', only because I'm going to hold off making any more structural changes to the way all these playbooks work/are installed until I work on a larger/more thorough second edition.
