### ISSUE TITLE
Deploy a version controlled application

### ISSUE THREAD

**Issue by objective-cnut** [geerlingguy/ansible-for-devops#544]
When running the ansible command 

_ansible app -b -m git -a "repo=git://example.com/path/to/repo.git dest=/opt/myapp update=yes version=1.2.4"_ 

The ansible command returns an error that the network is unreachable.

![Screenshot 2023-05-30 at 11 40 21](https://github.com/geerlingguy/ansible-for-devops/assets/17159402/24777e64-ec28-413e-9d49-d04c701e1884)

**Comment by dglinder** [comment]
Your error is because you're trying to clone from 'git://example.com/' which is a fictitious site.  For a functional test, you might want to use `https://github.com/geerlingguy/ansible-for-devops.git` or `https://github.com/geerlingguy/youtube.git` instead.

Since this is not a bug in the "Ansible for DevOps" book or examples (that I can find), I suggest @geerlingguy close this as "Not a bug".

@objective-cnut you should look on-line for general Ansible mailing lists and news groups for problems like this in the future and save the Git repositories for reporting genuine errors in the code contained within them.

**Comment by objective-cnut** [comment]
My apologies.
