### ISSUE TITLE
Book: chapter 3: "Faster OpenSSH in Ansible 1.5+"

### ISSUE THREAD

**Issue by msperl** [geerlingguy/ansible-for-devops#66]
Why don't you provide examples of how to use ansible to modify the /etc/sudoer on the fly with all the requirements for pipelining=true

That would be an exercise in itself.

**Comment by geerlingguy** [comment]
I think the way it currently reads (which follows, mostly, the documentation in the official project—https://docs.ansible.com/ansible/2.4/intro_configuration.html#pipelining) is okay, and since it's not necessary to have it enabled to use Ansible (it's more of a performance nice-to-have), I don't want to devote much more space to automating it.

Would be fine for someone to have some sort of 'ansible_performance_tuning' role on Ansible Galaxy though, for those who want to tweak things that way.

But even there, the way `ansible.cfg` configuration works, it would be impossible to do anything useful, generically, since there could be any number of config files that need to be changed for different projects, even individual servers.
