### ISSUE TITLE
Page 96: Add file for host2.

### ISSUE THREAD

**Issue by jdavid5815** [geerlingguy/ansible-for-devops#72]
If the example from the previous page is to be translated into separate yaml files, then for completeness sake, a yaml file for host2 should also be listed..

**Comment by geerlingguy** [comment]
I'm assuming this is in reference to the `Automatically-loaded \`group_vars\` and \`host_vars\`` section in Chapter 5? (It's hard to get a reference by page number since there have been 16 revisions to the print book already (it's on version 1.16 now)).

If so, not having a vars file for `host2` is quasi-intentional, because that shows that you don't need a host_vars file for each host, you can just put one in for any individual host which needs to have an overridden value.
