### ISSUE TITLE
False statement: Ansible is "provider-agnostic".

### ISSUE THREAD

**Issue by martinanderssondotcom** [geerlingguy/ansible-for-devops#75]
I don't know if this is the right forum for reporting issues with the book, but I didn't find any other way!

In chapter 8, in the summary of "Highly-Available Infrastructure with Ansible", the following is said:

> However, building infrastructure in a provider-agnostic fashion provides the agility and flexibility that allow you to treat hosting providers as commodities, and gives you the freedom to build more reliable and more performant application infrastructure.

This might only be false given the context, but nothing leading up to this paragraph of text shows that Ansible is "provider-agnostic". The only thing I have learned - thus far, and maybe I am wrong - is "agnostic", is the generic OS package module. Chapter 8 in particular, had to define separate playbooks for separate infrastructure providers! Nothing in these playbooks were "provider-agnostic".

I don't even like the term "abstract cloud provisioning" used in the preceding paragraph because this also implies one doesn't need to mind which infrastructure provider my playbook is targeting. But this just isn't true, at least the book has not until this page demonstrated Ansible as something agnostic. If this is done in a later section or chapter, then this should be made clear, preferably using a forward reference.

Let me take the moment to congrats on a great book using a very funny and entertaining language =) Love it!

**Comment by geerlingguy** [comment]
@MartinanderssonDotcom - Almost all the examples in the book, though, can be run on any VPS / VM running in any provider (I regularly test in VirtualBox locally, DigitalOcean, AWS, and often also in local Docker containers running Ubuntu 16/14, Debian 9/8, CentOS 7/6, Fedora 25/24...).

The example in Chapter 8 has two separate _plays_ that set up the provider-specific resources (e.g. droplets in DO, EC2 instances in AWS), but then the playbook as a whole (especially all the parts that set up services and configure things) can be run on either, just by including either digitalocean.yml or aws.yml.

Additionally, if you're using Ansible playbooks (and maybe even something like Ansible Container—working on a chapter on it right now) to set up containers to be deployed with openshift, k8s, in Google Cloud, in Amazon ECS, etc.), then the playbooks are 100% agnostic, since you're offloading the actual resource management to a cloud provider (or multiple).

So I think I'd stand by the provider-agnostic statement... there are always some things you have to tailor for local environment differences, but of Ansible's 2,000+ modules, only a few hundred of them will _only_ run in one particular provider's cloud environment.

I'll leave the issue open for more constructive debate... but this might be something fun to discuss more over in the Ansible Project Google Group :)

**Comment by jdavid5815** [comment]
While I love the simplicity, yet powerful features of ansible, other configuration management tools such as e.g. Puppet seem to care less about what OS a host is running. I'm not an expert but I concur with the original poster that ansible is not the most OS-agnostic tool out there. Still, it's way more user-friendly than any other configuration management tool, so it remains my preferred choice!

**Comment by geerlingguy** [comment]
I definitely see you point, and I think both our points stand. The way you interpret 'provider agnostic' is kind of 'in the eye of the beholder'.

I would argue Ansible is provider agnostic, but some of the modules are provider specific. CloudFormation is not provider agnostic, as it's tied to AWS. Terraform is provider agnostic, but most configurations you'll build with it are extremely provider specific. Kubernetes is provider agnostic, but most of the implementations people use in production are provider specific.

So I'm speaking in the more general sense, in that Ansible itself (as a tool and as part of the Red Hat organization) is not tied to any particular cloud service. One could make a (weak) argument that it's tied to OpenStack / OpenShift, but it's not really... it's meant to be the glue between pretty much all your infrastructure/networking/automation.

Anyways, the discussion can continue, but for now I'm leaving the book's wording as-is :) Truce!
