### ISSUE TITLE
node_npm_modules is treated literally on p136 (example line #7)

### ISSUE THREAD

**Issue by MaxSweat** [geerlingguy/ansible-for-devops#86]
Hi! So far so good with the book so far. Well written and informative - thanks!

This may be my bad, but on page 136, on example line no 7 it states we should use the following:

with_items: node_npm_modules

Using this, npm literally tries to install node_npm_modules as follows:

/bin/npm install --global node_npm_modules

If I change line no 7 to instead say:

with_items: "{{ node_npm_modules }}"

I get the desired and expected result. 

By all means flame me if I'm doing something wrong. Thanks!

**Comment by geerlingguy** [comment]
True! I'll make sure this is corrected soon and will close this issue once that's the case. Ansible actually used to allow the raw variable for with_items but only for a version or two... I fell into the bad habit of using it that way in 1.x, but since 2.x Ansible got strict—and you've found one of the places where I still haven't fixed the deprecated and now broken usage!

**Comment by geerlingguy** [comment]
It looks like this was actually updated a few months ago, but it might not be in a paperback copy if purchased earlier last year. It's up to date in the LeanPub and latest Kindle and iBooks editions of the book.

What version of the book do you currently have? I think this was fixed in 1.15 or 1.14. (The version is in the preface, under the section 'Please help improve this book!').

**Comment by MaxSweat** [comment]
Hi Jeff,

Thanks for following up on this. I bought the book a few weeks ago (in the
UK, hardcopy (call me old fashioned : -) )). The Preface says it's v1.15 of
the book.

Regards,
Richard
