### ISSUE TITLE
The box 'geerlingguy/ubuntu1404' could not be found

### ISSUE THREAD

**Issue by markovanderpuil** [geerlingguy/ansible-for-devops#88]
While trying your deployment examples:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'geerlingguy/ubuntu1404' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'geerlingguy/ubuntu1404' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/geerlingguy/ubuntu1404"]
Error: The requested URL returned error: 404 Not Found
```

**Comment by joestewart** [comment]
This should be fixed in Vagrant 2.0.3.

Reference https://github.com/hashicorp/vagrant/issues/9442 and possibly others

**Comment by markovanderpuil** [comment]
Perhaps we should add Vagrant 2.0.3 as a requirement?

**Comment by geerlingguy** [comment]
Another workaround is to delete your vagrant boxes locally (I think inside `~/.vagrant.d`) and then it will fix the problem. Unfortunately, there's not a ton I can do otherwise, as it's an upstream Vagrant bug. Hopefully it just goes away as 2.0.3 gets more widely distributed. Thanks for the issue report, closing it out as there's a fixed version now.
