### ISSUE TITLE
Broken link to HashiCorp's Atlas box repositories

### ISSUE THREAD

**Issue by bryankennedy** [geerlingguy/ansible-for-devops#99]
On page 11 you provide a link to Atlas:

> note: HashiCorp’s Atlas38 has a comprehensive list of different pre-made Linux boxes.

The Atlas link isn't valid any longer. Maybe replace with some language about using [Bento boxes](https://app.vagrantup.com/bento)

**Comment by geerlingguy** [comment]
@bryankennedy - Good catch! The new link is to https://app.vagrantup.com/boxes/search, though I do also use and recommend the Bento boxes quite often. But since the global search can get people more precisely what they need, I'll update the link to that.

I'll add a credit for the fix in the next published version of the book, thanks!
